# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  robertgenetti
title: Robert Genetti
email: robertkgenetti@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Personal website showing my recent coding adventures and resume 
  related content. Just an awesome way to get my name out there.

baseurl: ''
exclude: ['README.md']
permalink: pretty
exclude: vendor

# services -> projects
# team -> education
# features -> interests


collections:
  projects:
    output: true
    permalink: /projects/:path/
  education:
    output: true
  #   permalink: /education/:path/
  # interests:
  #   output: true
  #   permalink: /interests/:path/

defaults:
  - scope:
      type: projects
    values:
      layout: project
      bodyClass: page-services-single
  - scope:
      path: 'images'
    values:
      image: true

sass:
  style: compact # possible values: nested expanded compact compressed


# Build settings
plugins:
   - jekyll-environment-variables

#